version: '3.8'

services:

#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=cornel
#      - POSTGRES_PASSWORD=sefusefu
#      - POSTGRES_DB=mydatabase
#    networks:
#      - testKubernetesNetwork

  person-register:
    image: person-register-image:latest
    container_name: person-register
    ports:
      - 8080:8080
    networks:
      - testKubernetesNetwork
    depends_on:
      - postgres

networks:
  testKubernetesNetwork:
    driver: bridge