version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=mydatabase
    networks:
      - testKubernetesNetwork

networks:
  testKubernetesNetwork:
    driver: bridge