version: '3.8'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8181:8080

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

#  application
#  http://localhost:8080/person/
#  http://localhost:8080/person/actuator/metrics
#  http://localhost:8080/person/actuator/prometheus

#  prometheus
#  http://localhost:9090/
#  http://localhost:9090/config

#  cadvisor
#  http://localhost:8181/containers/

#  grafana
#  http://localhost:3000/
#  admin / admin